In [1]:
Name        : AKULLU DEBORAH
REG NO      : 2022/DCSE/OO5/SS
Date        : 29/07/2022
Task        : Test 1
Course unit : Mathematical computing
Note        : This note book contains solutions for the test

SyntaxError: invalid syntax (3933846710.py, line 1)

In [2]:
import numpy as np

In [3]:
#SECTION 2
# number 4
#generating a numpy array
x= np.array([25,2,5])
print(x)

[25  2  5]


In [4]:
#generating the shape of an array
x.shape


(3,)

In [5]:
#transpose of array x
x.transpose()


array([25,  2,  5])

In [7]:
# number 5
#generating a numpy array
X=np.array([[25,2],[5,26],[3,7]])
print(X)

[[25  2]
 [ 5 26]
 [ 3  7]]


In [8]:
#1.generating its shape
X.shape

(3, 2)

In [9]:
#2.generating its transpose
X.transpose()

array([[25,  5,  3],
       [ 2, 26,  7]])

In [10]:
#3. generating matrix A
A=np.array([[3,4],[5,6],[7,8]])
print(A)

[[3 4]
 [5 6]
 [7 8]]


In [14]:
#3. multiplication of X and A
print(X*A)


[[ 75   8]
 [ 25 156]
 [ 21  56]]


In [17]:
#4. inverse of the product of A and X
#let the product of A and X be C
#there fore;
C=np.array([[75,8],[25,156],[21,56]])
print(C)


[[ 75   8]
 [ 25 156]
 [ 21  56]]


In [ ]:
print(np.linalg.inv(C))

In [23]:
#number 6
#part a
#let the matrix be m
m=np.array([1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1])
print(m)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [24]:
m.transpose()

array([[1. , 0.2, 0.5],
       [0.2, 1. , 0.8],
       [0.5, 0.8, 1. ]])

In [33]:
#part b
det=np.linalg.det(m)
print(int(det))

0


In [ ]:
#SECTION 1
#number 1    
D .0.019

#NUMBER 2
B . 0.050%

#number 3
B  . 0.5210

#NUMBER 4
A. Pr(Monday|rain)

#number 5
C. The Probability that it is Monday, given that it is raining

#number 6
B. Pr(rain|Monday)

#number 7
A. Pr(AnB) = Pr(A)+Pr(B)

#number 8
D. Insufficient Information provided
this data suggest that "getting an A" and "living on campus"  independent

#number 9
#part (a)
 D. Insufficient Information provided
there are 12 options

#number 10
#part (a)
B. 0.501
#part (b)
(3) 0.430



